excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
opt_in_rules:
- empty_count
- empty_string
line_length:
    warning: 150
    error: 200
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 600
file_length:
    warning: 1000
    error: 1500
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
